# Generated by Django 5.0.1 on 2024-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='cover_letter',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='first_name',
            new_name='job_position',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='last_name',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
        migrations.AddField(
            model_name='candidate',
            name='company_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(default='react'),
        ),
    ]
